### ISSUE TITLE
undefined method `first' ... rack_app = Rack::Builder.parse_file(config_ru).first

### ISSUE THREAD

**Issue by zblsv** [sickill/racksh#17]
https://github.com/sickill/racksh/blob/65c35251a9c830fcc6f39fe03972897ebc110f88/lib/racksh/init.rb#L23

In Rack-3 Rack::Builder.parse_file returns simply application object.
So must be
`rack_app = Rack::Builder.parse_file(config_ru)`
without .first

With correction of the now missing File.exists? racksh works for me on Ruby-3.2.2 and Rack-3.0.7

**Comment by dentarg** [comment]
Fixed by https://github.com/sickill/racksh/pull/13 that was released with 1.0.1
